### ISSUE TITLE
The image snapshot handler for the given accessory is slow to respond!

### ISSUE THREAD

**Issue by iuliusmaximilian** [Sunoo/homebridge-camera-ffmpeg#1064]
**Describe The Problem:**
Up to now I was running a Rasp. 3 with manually installed homebridge and FFmpeg in conjunction with the Reolink configuration described here. For 8 cameras mostly RLC-410 PoE this worked fine and I received rich notifications for all of them triggered via HomeKit automations. Because of a hardware defect some days ago I moved to a fresh installed Rasp. 4 8GB and installed everything via the Homebridge UI.

Now, I am able to receive snapshots from all cameras as well as streams again. What is not working anymore are rich notifications. Yesterday I replaced 3 of 8 cameras by the new RLC-810A/RLC-820A and these once have a channel for more low resolution snapshots. Since I changed these three to lowres, these three are sending rich notification but still for others I do receive notification without any snapshot and this worked before moving to my new Rasp. 4.

**To Reproduce:**
Always the same behaviour.

**Logs:**
[homebridge.log.txt.zip](https://github.com/Sunoo/homebridge-camera-ffmpeg/files/6100310/homebridge.log.txt.zip)

**Homebridge Config:**
[config.json.zip](https://github.com/Sunoo/homebridge-camera-ffmpeg/files/6100271/config.json.zip)

**Environment:**

* **Node.js Version**: v15.11.0
* **NPM Version**: Console 7.6.0 BUT Homebridge UI shows v6.14.11
* **Homebridge Version**: Initializing HAP-NodeJS v0.9.2... 1.3.2
* **Homebridge Camera FFmpeg Version**: ffmpeg version 4.1.6 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --disable-decoder=amrnb --disable-decoder=libopenjpeg --disable-libopencv --disable-outdev=sdl2 --disable-podpages --disable-sndio --disable-stripping --enable-libaom --enable-avfilter --enable-avresample --enable-gcrypt --disable-gnutls --enable-openssl --enable-gpl --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libzimg --enable-libxvid --enable-libzvbi --enable-nonfree --enable-opencl --enable-opengl --enable-postproc --enable-pthreads --enable-shared --enable-version3 --enable-libwebp --incdir=/usr/include/arm-linux-gnueabihf --libdir=/usr/lib/arm-linux-gnueabihf --prefix=/usr --toolchain=hardened --enable-frei0r --enable-chromaprint --enable-libx264 --enable-libiec61883 --enable-libdc1394 --disable-altivec --shlibdir=/usr/lib/arm-linux-gnueabihf
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

* **Homebridge Config UI X Plugin Version**: v1.3.2
* **Operating System**: Rasp 4 latest update/upgrade

**Comment by Sunoo** [comment]
Sorry for the slow response, I've been working primarily from my iPad for the past few days, so couldn't easily open your ZIPs.

I'm a bit confused here though. For starters, I don't actually see the "slow to respond" messaging in the log you uploaded, and it looks like the snapshots are being pulled in less than 2 seconds.

That said, there isn't much I can do about that messaging, some cameras just take a while to return the first frame of video, and if it takes over 5 seconds, that message is written to the log. It looks like you're already running your cameras in unbridge mode, so that slowness shouldn't impact any other devices on the bridge though.

**Comment by iuliusmaximilian** [comment]
Its so strange but replacing some LAN kabels solved it, really don’t know why.

**Comment by sebastiaan88** [comment]
I would like to add a note which helped me solve this for my HikVision cameras after hours of searching, since they don't pull a snapshot from the sub stream but only main (which is almost 4k 512kb image!) I finally fixed this by adding extra parameters to url:  -vf scale=640:-1 (sub stream is 640x360) now it only takes 2s max! Also note that in the HikVision camera its best to set Authentication "digest/basic" and turn on CGI platform to enable snapshot images.

`"stillImageSource": "-i http://user:pass@ip.range/Streaming/channels/102/picture -vf scale=640:-1",`
