### ISSUE TITLE
Tp-Link Tapo C310 HomeKit Integration through Homebridge

### ISSUE THREAD

**Issue by vipii** [Sunoo/homebridge-camera-ffmpeg#1348]
I am trying to add my camera to homekit through Homebridge.

I am using the homebridge-camera-ffmpeg package
https://github.com/Sunoo/homebridge-camera-ffmpeg

They are clearly visible in homekit, the thumbnails refresh every now and then so they are clearly working.

But when I try to open the stream it does not work.
Homekit does report:
[10/7/2022, 10:20:58 PM] [Camera FFmpeg] [Cam Outdoor] Starting video stream: 1280 x 720, native fps, 299 kbps (AAC-eld)
[10/7/2022, 10:21:01 PM] [Camera FFmpeg] [Cam Outdoor] Stopped video stream.

Setup:
{
"name": "Cam Outdoor",
"manufacturer": "TP-Link",
"model": "C310",
"motion": true,
"unbridge": true,
"videoConfig": {
"source": "-i rtsp://USER:PASSWORD@IP:554/stream1",
"maxStreams": 5,
"maxWidth": 1280,
"maxHeight": 720,
"maxFPS": 0,
"forceMax": true,
"audio": true
}
}

**Comment by jlg89** [comment]
Try adding "vcodec": "libx264", before the "audio": true line.

**Comment by macbookalu** [comment]
Similar issue here

I have 2 Tapo C100, 1 Tapo C200, and since yesterday a C310. C100 and also C200 works fine in home-app through Homebridge and Camera-ffmpeg. But the C310 are giving me a bunch  of errors.

Here is my config.json 

`	"platform": "Camera-ffmpeg",
			"cameras": [{
					"name": "Camara Habitación Gatos",
					"manufacturer": "TP-Link",
					"model": "C100",
					"motion": true,
					"unbridge": true,
					"videoConfig": {
						"source": "-rtsp_transport http -re -i rtsp://USER:PASS@192.168.0.XXX:554/stream1",
						"maxStreams": 2,
						"maxWidth": 1280,
						"maxHeight": 720,
						"maxFPS": 15,
						"maxBitrate": 300,
						"packetSize": 188,
						"vcodec": "libx264",
						"audio": false,
						"debug": false

					}
				},
				{
					"name": "Camara Salón",
					"manufacturer": "TP-Link",
					"model": "C200",
					"motion": true,
					"unbridge": true,
					"videoConfig": {
						"source": "-rtsp_transport http -re -i rtsp://USER:PASS@192.168.0.XXX:554/stream1",
						"maxStreams": 2,
						"maxWidth": 1280,
						"maxHeight": 720,
						"maxFPS": 15,
						"maxBitrate": 300,
						"packetSize": 188,
						"vcodec": "libx264",
						"audio": false,
						"debug": false
					}
				},
{
"name": "Camara Patio",
"manufacturer": "Tapo",
"model": "C310",
"motion": true,
"motionTimeout": 15,
"unbridge": true,
"videoConfig": {
"source": "-rtsp_transport tcp -re -i rtsp://USER:PASS@192.168.0.XXX:554/stream1",
"maxStreams": 2,
"maxWidth": 1920,
"maxHeight": 1080,
"maxFPS": 15,
"vcodec": "libx264",
"audio": false,
"debug": false
}
				},
				{
					"name": "Camara Habitación",
					"manufacturer": "TP-Link",
					"model": "C100",
					"motion": true,
					"unbridge": true,
					"videoConfig": {
						"source": "-rtsp_transport http -re -i rtsp://USER:PASS@192.168.0.XXX:554/stream1",
						"maxStreams": 2,
						"maxWidth": 1280,
						"maxHeight": 720,
						"maxFPS": 15,
						"maxBitrate": 300,
						"packetSize": 188,
						"vcodec": "libx264",
						"audio": false,
						"debug": false
					} `

Any help?
