### ISSUE TITLE
Report No Response from a camera to HomeKit that has issues with stream

### ISSUE THREAD

**Issue by sweetw0r** [Sunoo/homebridge-camera-ffmpeg#1386]
**Is your feature request related to a problem? Please describe:**

When my Nanit camera has stream issues it is not obvious from Hime app until I open the camera to see and after attempt of loading it shows “No response”. 

**Describe the solution you'd like:**
It would be better if “No response” state has been shown in Home app notifications. Signaling that actions might be needed. Just like it works with other devices. E.g. Hue Lights if switched was manually turned off and thus “No response” gets repeated to Home app

![27599F20-3D17-4718-94F3-82F3C0A55909](https://user-images.githubusercontent.com/12688470/223509164-110874d7-7b08-4fcd-981a-92a57183b0b3.jpeg)

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Sunoo** [comment]
Due to the way all of this works, it’s very difficult to handle it that way. This plugin never really directly attempts to connect to the cameras, instead allowing FFmpeg to handle all that work, and it’s not worth spinning up all that just to “ping” the camera and see if it’s responding. Plus doing that ping could cause additional issues where no response is reported to HomeKit for a camera that perhaps has too many connections going to it already, but would work just fine a few seconds later when a stream was disconnected.

If someone can think of a better way, I’d be open to it, but for now I think this is the best we can do.
