### ISSUE TITLE
Rich notification with MQTT

### ISSUE THREAD

**Issue by olleg** [Sunoo/homebridge-camera-ffmpeg#771]
I am using MQTT broker to activate motion sensor. All work fine and motion notification is delivered to my devices. However, the notification is not rich and doesn't have a preview picture. 

When I turn on "switches" feature and manually activate the switch, then I receive notification with preview. Yes, I can create another fake motion sensor and activate switch, which will activate another motion sensor and send notification, but to me it seems overcomplification and I am looking for more elegant solution. 

Is there something I might be doing wrong with my setup?

**Comment by NorthernMan54** [comment]
Did you follow this?

https://sunoo.github.io/homebridge-camera-ffmpeg/automation/

**Comment by Sunoo** [comment]
That’s odd, assuming everything is configured right. Switches, HTTP, and MQTT all activate literally the exact same code when triggered. If it works via one method, there is no reason it shouldn’t work by any of the others.

**Comment by olleg** [comment]
After some experiments I started to see rich messages using MQTT messages to initiate motion detector. However, only part of the messages are rich. Can this be that camera is pending the stall image provision and therefore system decide to send notification without picture? 

Perhaps there needs to be some awaiting of the picture implemented?

I am using two cameras by different producers: Reolink and Hikvision. They both react same.

**Comment by Sunoo** [comment]
If your cameras are very slow to respond, eventually HomeKit will stop waiting for a snapshot.

An easy way to tell how slow your camera is is to watch you camera snapshots update in the Home app while on wifi. Home will request a new snapshot every 10 seconds, so let me know what the timer in the corner of the snapshot gets to before resetting to “now”. Anything over 10 seconds would be delay due to your camera.
